import sys
import time
import vlc
G = vlc.MediaPlayer("C:/Users/steam/OneDrive/Masaüstü/lifesim/lifesimmp.mp3")
G.play()


a = 2
b = 0.2
c = 0.08


def intro():
    print()
    print("################################################################################")
    print()
    
    print("Türkiyede yaşıyorsun ve lisen bitti 2 ay sonra bir telefon geldi")
    time.sleep(a)
    print("Arayan kuzenindi seni yanına avrupaya çağrıyordu")
    time.sleep(a)
    print("Ama sen istediğin üniversite bölümünü kazanmıştın bile")
    time.sleep(a)
    print("Okumayıp erkenden hayata atılabilirsin")
    time.sleep(a)
    print("Avrupayamı gideceksin ,Türkiyede kalıp okucakmısın yoksa işe girip çalışcakmısın?")
    time.sleep(a) 
    print()
    time.sleep(a) 
    print("Parça #1: Avrupaya taşın")
    time.sleep(a) 
    print("Parça #2: Üviversiteye git ")
    time.sleep(a) 
    print("Parça #3: Türkiyede çalış")
    time.sleep(a)
    print()
    
    firstpath = input ("Hangi yolu tercih ediceksin (1/2/3): ")
    if firstpath == '1' :
        print()
        path1()
    elif firstpath == '2' :
        print()
        path2()
    elif firstpath == '3' :
        print()
        path3()   

def path1():
    print()
    print("################################################################################")
    print("|                                                               @              |")
    print("|                                                          /@@@@%              |")
    print("|     ,&                              %((,           *. @%@@@@@@#              |")
    print("|    %@@@@@@                      ,@@@@@@@@@@@@/    #  @@@@@@@@@               |")
    print("|      . .,                     #&@@@@@@@@@@@@@@@@,/ @@@@@@@@@@@@              |")
    print("|                              @@@@@@@@@@@@@@@&   *@@@@@@@@@@@@@@@@            |")
    print("|                            ,@@@@@@&  @@@@@@@@@/*@@@@@@@@@@@@@@@@@@           |")
    print("|                         %@@@@@@@@/ (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%         |")
    print("|                *     #@@@@@@@@@#   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#         |")
    print("|          ..%@.       %@@@@@@@@@@.   @&   ./@@@@@@@@@@@@@@@@@@@@@@@@@@ ./     |")
    print("|           &@@.       /@,  @@@@@/    .&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ .   |")
    print("|     @&@@,#@@@           , &@@@#    @@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@  |")
    print("|   (@@@@   .@@&        ,//@ @       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  *       |")
    print("|        .%@@@@%#     ,.(@&#@. #@@#%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#            |")
    print("|       ,..*#@@&  /@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*             |")
    print("|      .*( // %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,/           |")
    print("|         @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@          |")
    print("|         ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%,&@@@@@@@@@@           |")
    print("|,@@@&     .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&   *@, *%@@@@@@@@@@@@%       |")
    print("| @@@@@@@@@@@@@@@@@@@@@@@@, &&@@@@@@@@@@@@@@@@,             ./@@@@@@@@@@#      |")
    print("| #@@@@@@@@@@@@@         /@@@%  *&@@@@@@@@@@@@@%                   ,@@@@@@@&   |")
    print("| @@@@@@@@@@&           &   %@@@     %@@@@@@@@@@@                              |")
    print("| #@@@@@@@@& /         %&      *@@@@  @@@@/@   #                               |")
    print("|                             @&    ,@@/                                       |")
    print("|                         /@@         @/#                                      |")
    print("################################################################################")
    print()
    print("Avrupaya gittin ama uzun süre geçmesine ramen düzen kuramadın...")
    time.sleep(a)
    print("Her şeye ramen seni idare edicek bir işin var.")
    time.sleep(a)
    print("Ailen ve arkadaşlarından ayrı yaşadığın için kendini bunalmış hissediyorsun :(")
    time.sleep(a) 
    print("İçinden bir ses seni türkiyeye dönmem gerektiğini söylüyor...")
    time.sleep(a) 
    print()
    time.sleep(a)
    print("Parça #1: Türkiyeye Ailenin & Arkadaşlarının arasına dön")
    time.sleep(a) 
    print("Parça #2: Avrupada Kalmaya devam et")
    print()
    time.sleep(a) 
    secondPath = input("Hangisini Seçiceksin (1/2): ")
    if secondPath == '1':
        path1_1()
    elif secondPath == '2':
        path1_2()

def path1_1():
    print()
    print("################################################################################")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                  @@@@.         @@@                           |")
    print("|                             @@@@@@@@@@@@@@%    @@@                           |")
    print("|                        @@@@@@@@@@#   @@@@@@@@@@@@@@                          |")
    print("|                  ,@@@@@@@@@@*   %@@@@#    @@@@@@@@@@@                        |")
    print("|              @@@@@@@@@@.   @@@@@@@@@@@@@@@@    @@@@@@@@@@@                   |")
    print("|              @@@@@.   @@@@@@@@@@@@@@@@@@@@@@@@@@    *@@@@@                   |")
    print("|                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          |")
    print("|                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          |")
    print("|                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          |")
    print("|                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                          |")
    print("|                    @@@@        (@@@     @@    @@@@@                          |")
    print("|                    @@@@        (@@@     @@    @@@@@                          |")
    print("|                    @@@@        (@@@     @@    @@@@@                          |")
    print("|                    @@@@        (@@@%%%%%@@%%%%@@@@@                          |")
    print("|                    @@@@        (@@@@@@@@@@@@@@@@@@@                          |")
    print("################################################################################")
    print()                                                                                               
    
    print("Türkiyeye Ailen & arkadaşlarının yanına döndün ama hiç birşey eskisi gibi güzel değildi..")
    time.sleep(a) 
    print("Uzun zamandır Türkiyede çok şey değişmişti yaşam şartlarıda iyi sayılmazdı")
    time.sleep(a) 
    print("Türkiye taşındıktan sonra asgari ücretli bir işe girdin yarı aç yarı tok şekilde yaşamaya çalıştın")
    time.sleep(a) 
    print("Aldığın maaş ev masraflarına yetmiyordu bir gün parasızlıktan işten eve dönerken araba çarpma sonucu ağır yaralandın")
    time.sleep(a) 
    print("Hastaneye kaldırıldın ziyaretine sadece Annen ve Kız kardeşin geldi")
    time.sleep(a) 
    print("Hastaneye kaldırıldıktan sonra genel yoğun bakım bölümünde sana bakan hemşir tarafiından darp ediliyordun")
    time.sleep(a) 
    print("Bir süre sonra artık seni ziyarette kimse gelmiyordu ne arkadaşın nede ailen bazı geceler içten içe ağlıyodun")
    time.sleep(a)
    print("Acılarına daha fazla dayanamadın, solunum yetmezliğinden hayata gözlerini yumdun....")
    time.sleep(a) 
    print()
    time.sleep(a) 
    print("Oyun Bitti")
    time.sleep(a) 
    print()


def path1_2():
    print()
    print("################################################################################")
    print("|                             %                                  . .     . .   |")
    print("|. .     . .     . .     %%%(%%%%%%%     . .     .       . .     . .     . .   |")
    print("|                      %#..,%%%%#....%          %%%%%%%%%%                     |")
    print("|. .     . .     . .  %...............%  . .  %%%%%%%%%%.%%%     . .     . .   |")
    print("|                      .................      %.,**...........                 |")
    print("|. .     . .     . .   .... ..........   .   .....(..../.....(   . .     . .   |")
    print("|                        ....,/*....        %%..............%%                 |")
    print("|. .     . .     . .         ....        .  %%%%...////...%%%%   . .     . .   |")
    print("|                        (@@@ @ (@@@        %%%%%%%#%..**%%%%%%                |")
    print("|    . .     . .     . @@@@@@ @  @@@@@       . #%%%,.*....%  . .     . .     . |")
    print("|                    ,@@@@@@  @  @@@@@@@      %%%%%%%*%..%%%                   |")
    print("|    . .     . .    @@@  @@@ .@@ @@@  @@@    .. ********/%*..  .     . .     . |")
    print("|                  %@@   @@@  @  @@@   @@&  ..  *****.........                 |")
    print("|    . .     . .   @@    @@@  .  @@@   *@@ ..    (*****((    . .     . .     . |")
    print("|                 ...    @@@@@&@&@@@    ....    ((((((((((                     |")
    print("|. .     . .     ...     @@@@   &&@@     .     ((((((((((((      . .     . .   |")
    print("|                        @@@@   @&@&           ((((((((((((                    |")
    print("|. .     . .     . .     @&&@   @&&&     . .  ((((((((((((((     . .     . .   |")
    print("|                        @&&@   @@&@              .. ...                       |")
    print("|. .     . .     . .     @@@%   @@@@     . .      .. ..  . .     . .     . .   |")
    print("|                       @@@@@   @@@@@             .. ..                        |")
    print("################################################################################")
    print()
     
    print("Avrupada kalmaya devam ettin ve bazı şeylerin değişmesi gerektiğine karar verdin")
    time.sleep(a) 
    print("Hayatını yoluna soktun ve bir kadınla tanışıp evlendin")
    time.sleep(a) 
    print("2 Çocunuz oldu ve mutlu mesut yaşadınız")   
    time.sleep(a) 

def path2():
    print()
    print("################################################################################")
    print("|  . .. .  . .  . .. .  . .. . .. .  . .. .  . .  . .. .  . .  . .. .  . .  . ..|")
    print("|.. .  . .. .  . .  . .. .  . .  . .. .  . .  . .. .  . .. . .. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  . .. .  . .  . ..  @@@@@  . .. .  . .. . .. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  . .. .  . .  . @@@@@@@@@@@@@.. .  . .. . .. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  . .. .  . .  . @@@@  . .@@@@.. .  . .. . .. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  . .. @  . .  . @@@@@ . @@@@@.. .  . .@ . .. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  . .@ @ @.@@@@@@@@@@@@@@@@@@@@@@@@@.@.@ @ .. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  .@@@@@  &@@@ .@@@ . @@@. @@@@. @@@* .@@@@@. .  . .. .  . .  |")
    print("|.. .  . .. .  . .  .@@@@@  &@@@ .@@@ . @@@. @@@@. @@@* .@@@@@. .  . .. .  . .  |")
    print("|                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                  |")
    print("|  . .. .  . .  . .. @@@@@..&@@@. @@@  .@@@  @@@@ .@@@*. @@@@@ . .. .  . .  . ..|")
    print("| . .. .   . .   . ..@@@@@..&@@@. @@@  .@@@  @@@@ .@@@*. @@@@@ . .. .  . .  . ..|")
    print("|  . .. .  . .  . .. @@@@@  &@@@  @@@   @@@  @@@@  @@@*  @@@@@ . .. .  . .  . ..|")
    print("|  . .. .  . .  . .. @@@@@..&@@@. @@@  .@@@  @@@@ .@@@*. @@@@@ . .. .  . .  . ..|")
    print("|  . .. .  . .  . .. @@@@@..&@@@. @@@  .@@@  @@@@ .@@@,. @@@@@ . .. .  . .  . ..|")
    print("|  . .. .  . .  . .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ .. .  . .  . ..|")
    print("|. .. .  . .  . .. .  . .. . .. .  . .. .  . .  . .. .  . .  . .. .  . .  . ..  |")
    print("################################################################################")
    print()
    
    print("Üniversite okumaya karar verdin ve aradan 1 sene geçmişti.")
    time.sleep(a) 
    print("Yaz tatiline az kalmıştı derslerinde çok kötü değildi")
    time.sleep(a)
    print("Çalışmaların meyvesini yavaş yavaş vermeye başlamıştı ama arkadaş ortamın yoktu vede paran")
    time.sleep(a) 
    print("Ailen aradı ve daha fazla destek olamicaklarını söylediler çünkü Baban iş kazasında vefat etmişti")
    time.sleep(a) 
    print("Bir yandan dersler bir yandan işe girip çalışman lazımdı")
    time.sleep(a) 
    print()
    print("Parça #1: Okumayı bırak işe girip ailene destek ol")
    time.sleep(a)
    print("Parça #2: Sabahları Okula git akşamları çalış harçlık çıkar")
    time.sleep(a) 
    print()
    time.sleep(a) 
    secondPath = input("Hangisini Seçiceksin (1/2): ")
    time.sleep(a) 
    if secondPath == '1':
        path2_1()
    elif secondPath == '2':
        path2_2()

def path2_1():
    print()
    print("################################################################################")
    print("|                                  @@@@                                        |")
    print("|                          /@@@@@@     (@@@@@@@                                |")
    print("|                        @@@                  @@@@                             |")
    print("|                      @@                       (@@@                           |")
    print("|                     @@                          @@@                          |")
    print("|                     @@  @                     @ @@@                          |")
    print("|                     @@  @                    @@ @@@                          |")
    print("|                      @@ @   @@@@@     @@@@@  @/@@@                           |")
    print("|                       @@@ @@@@@@@    @@@@@@@ @@@@                            |")
    print("|                @@ @@  @@   @@@@@@     @@@@@@  @@@   @@@@@                    |")
    print("|               @@    @@@@         *@@@         @@@@@@*  @@                    |")
    print("|              @@@@@@@@@  @@@@/    @@ @@     @@@@     @@  @@                   |")
    print("|                      %@@@@@ @@          @@@ @@@@@@@%                         |")
    print("|                          @@     @ *@@ @@ @  @@                               |")
    print("|                        @@@@   @ @  @  @ @  @@@@                              |")
    print("|               %@@@@@@@    @@@@           @@@,  @@@@@@@@@                     |")
    print("|                 @@   @@@@@@  @@@@@    @@@@ @@@@@      @@                     |")
    print("|                 (@@@@            (@@@(          ,@@ @@                       |")
    print("|                                                                              |")
    print("################################################################################")
    print()
   
    print("Okumayı bıraktın işe girdin artık Ailene baktıyordun ve kız kardeşini okutuyodun...")
    time.sleep(a) 
    print("Kafanı yastığa koydun, daha 19 yaşındaydın ama sanki dünyanın yükü omzunda gibi hissediyordun")
    time.sleep(a) 
    print("Sonra senden daha kötü durumda olan insanlar aklına geldi bi nebze olsun daha iyi hissetin")
    time.sleep(a) 
    print("2 yıl sonra Annen kanser hastalığı yüzünden vefat ediyor")
    time.sleep(a) 
    print("Hayatta değer verdiğin insanların kaybı git gide piskolojini bozuyor")
    time.sleep(a) 
    print("Annen öldükten 3 ay sonra hayatın anlamsız bir yarış olduğunu ve yorulduğunu düşünüp")
    time.sleep(a) 
    print("Evindeki siyanürü kokladın(0,3 gr), kokladıktan  bir kaç dakika sonra hızlı ve derin nefes almaya başlıyodun")
    time.sleep(a) 
    print("ardından akabinde çırpınma & bilincin kapanıyor ölüyorsun...")
    time.sleep(a)

def path2_2():
    print() 
    print("################################################################################")
    print()                                                            
    
    




    
    print("Çalışıp okumayı seçtin, sabahları okula okul çıkışı işe gidiyordun")
    time.sleep(a) 
    print("Eve geldiğin zamanlar çok yorun oluyodun buan ramen ders çalışmaya devam ettin")
    time.sleep(a) 
    print("Üniversiteyi zar zor bitirdin iş bulmamıyordun.")
    time.sleep(a) 
    print("1 Yıl boşta kaldıktan sonra mezun olduğun bölümden iş teklifi aldın")
    time.sleep(a) 
    print("5 Yıl aradan sonra terfi aldın ve sakin bir hayat yaşadın...") 
    time.sleep(a)   

def path3():
    print()
    print("################################################################################")
    print("|                                                                              |")
    print("|                                             @  (@                            |")
    print("|                                          @&      @                           |")
    print("|                                               ,@@@@@                         |")
    print("|                                               @@@@@@                         |")
    print("|                                               @@@@@@                         |")
    print("|                        @        @        @    @@@@@@                         |")
    print("|                      @@@&     @@@      @@@    @@@@@@.                        |")
    print("|                   @@@@@@& &@@@@@@  @@@@@@@   .@@@@@@@                        |")
    print("|                 @@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@                        |")
    print("|                 @@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@                        |")
    print("|                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,                    |")
    print("|                 @@@@       @@@@@       @@@@@       @@@@@.                    |")
    print("|                 @@@@       @@@@@       @@@@@       @@@@@.                    |")
    print("|              @@@@@@@       @@@@@       @@@@@       @@@@@@@                   |")
    print("|              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   |")
    print("|              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   |")
    print("|             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                    |")
    print("################################################################################")
    print()                                                                             
     
    print("Türkiyede Kalıp Çalışmayı seçtin")
    time.sleep(a) 
    print("Genç yaşta iş hayatına atıldın")
    time.sleep(a) 
    print("25 Yaşına girmiştin ve elinde sermayen vardı bu para ile gıda sekötürnde yatırım yapmak istiyordun")
    time.sleep(a) 
    print("Yada paranla bir araba & iphone x alıp her gün 15465465418979 hikaye atabilirdin")
    time.sleep(a) 
    print()
    print("Parça #1: Gıda sektörüne yatırıp yap")
    time.sleep(a) 
    print("Parça #2: Araba & iphone x Satın al.")
    time.sleep(a) 
    print()
    time.sleep(a)
    secondPath = input("Hangisini Seçiceksin (1/2): ")
    time.sleep(a) 
    if secondPath == '1':
        path3_1()
    elif secondPath == '2':
        path3_2()

def path3_1():
    print()
    print("################################################################################")
    print("|                                                                              |")
    print("|                                             @  (@                            |")
    print("|                                          @&      @                           |")
    print("|                                               ,@@@@@                         |")
    print("|                                               @@@@@@                         |")
    print("|                                               @@@@@@                         |")
    print("|                        @        @        @    @@@@@@                         |")
    print("|                      @@@&     @@@      @@@    @@@@@@.                        |")
    print("|                   @@@@@@& &@@@@@@  @@@@@@@   .@@@@@@@                        |")
    print("|                 @@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@                        |")
    print("|                 @@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@                        |")
    print("|                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,                    |")
    print("|                 @@@@       @@@@@       @@@@@       @@@@@.                    |")
    print("|                 @@@@       @@@@@       @@@@@       @@@@@.                    |")
    print("|              @@@@@@@       @@@@@       @@@@@       @@@@@@@                   |")
    print("|              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   |")
    print("|              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   |")
    print("|             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                    |")
    print("################################################################################")
    print()
    
    print("Tüm sermayeni gıda firması açmak için kullandın")
    time.sleep(a) 
    print("Başta işler berbat gidiyordu hayvanların giderleri gelirlerinden yüksekti böyle giderse 3 aya kalmaz batıcaktın")
    time.sleep(a) 
    print("Sonra aklına fikir geldi... Hayvanların gıda masraflarını satın alcağın arazilerden ekip karşılıcaktın")
    time.sleep(a) 
    print("Yine hayvanların giderleri gelirleri geçmeze bu sefer bankadan alcağın krediyi ödiyemicen?")
    time.sleep(a) 
    print("Çifliği satıp normal yaşantına dönebilirsin..")
    time.sleep(a)
    print()
    print("Praça #1: Bankadan kredi çek arazi satın al Hayvansal gıdalar ek")
    time.sleep(a) 
    print("Parça #2: Çifliği satıp eski hayatına dön")
    time.sleep(a) 
    print()
    time.sleep(a) 
    secondPath = input("Hangisini Seçiceksin(1/2): ")
    time.sleep(a) 
    if secondPath == '1':
        path3_1_1()
    elif secondPath == '2':
        path3_1_2()  
        



def path3_1_1():
    print()
    print("################################################################################")                                                                                                                                                          
    print("|                    /%#%%%%             ##  ,,*                               |")
    print("|                  %###(((#((#%#           ***                                 |")
    print("|                 %##((((#((#((#%         % % *                                |")
    print("|                 %%%%%##%%%%###%%          %                                  |")
    print("|                  /**,*,**,***/    ################                           |")
    print("|                  ****,/@@*,**/####%%/////*(*///(/%###%                       |")
    print("|                  /***,@@@@,*%#(%((/*/*/**/(***/(*//(%(#%                     |")
    print("|                  /***,,*,*,%#(#(/(*/&&@@@@@@@@&&&//(/##(%                    |")
    print("|                  /***,**,,(#(#%/*(*/&&&(((((((&&&/*(/(%##%                   |")
    print("|                  ****,*,**,**(//*(/*(%#(((#((##(%**(/((                      |")
    print("|                  ***,*@@@@,**(///(**/*/**/(////(***(//(                      |")
    print("|                  ***,,@@@@,**((//(//**///*(*/**(//*(/((                      |")
    print("|                  ##########%#(///(/*((@@@@#@@@@(#/*(//(                      |")
    print("|                  /***,,***,**((//(/*%@#((@#@((%@(*/(/((                      |")
    print("|                  /****,,,****(///(*/%@@@@((@@@@@(//(//(                      |")
    print("|                  *****,*,****((//(//%@((@@#@#((@(//(/((/                     |")
    print("|                (/#&&//////*&&&&&&&&&@@@@@@@&@@@@@&&&%&&//(                   |")
    print("|                 //////***************************/*////(/                    |")
    print("|                      *(/(///////////////////////(((,                         |")
    print("################################################################################")
    print()                                                                                                                                            
  
    print("Bankadan parayı çekip araziyi satın aldın")
    time.sleep(a) 
    print("Verdiğin karar ile firmanı kuratardın hem masraflarını %90 indirmiştin")
    time.sleep(a) 
    print("3-4 Yıl  içersinde ürettiğin gıdalar market raflarında satılıyordu gelen paranın bir çoğunu firmanı geliştirmek için kullandın")
    time.sleep(a) 
    print("Lise mezunu olarak başladığın bu yolda fabrikatör olarak son verdin... Tebrikler.")
    time.sleep(a) 
    print()
    print("Eğer bir şeyi yapmak istiyorsan, şimdi yap. Yapmazsan, pişmanlık duyacaksın.” – Catherine Cook")
    time.sleep(a) 






def path3_1_2():
    print()
    print("################################################################################")
    print()
    print("Çifliği satıp yaşadığın standart hayatına döndün")
    time.sleep(a) 
    print("Firmayı açtın paranın sadece yarını geri alabilmiştin")
    time.sleep(a) 
    print("Büyük bir firmada çalışmaya başladın, 68 Yaşında aşırı sigara kullanımından öldün..")
    time.sleep(a)


    



def path3_2():
    print()
    print("################################################################################")
    print()
    print("Araba & iphone x aldın artık insanlar senin heg gün attığın 15465465418979 hikayeyi görmek zorunda klalıcak :)")
    time.sleep(a) 
    print()
    print("Son")
    time.sleep(a)    




print()
print()
print("  #######################")
print("  |                     |")
print("  |       Life Sim      |")
print("  |                     |")
print("  #######################")
print()
print()
print("Life Sim oyununa hoş geldin....")
time.sleep(a)
print("Verdiğin kararlar karakterinin hayatını şekillendircek.")
time.sleep(a)
print()
startGame = input("Oyuna Başlamak İstermisin (E/H):")
if startGame == 'h' or startGame == 'H':
    print("Belki başka zaman")
elif startGame == 'e' or startGame == 'E':
    intro()
input()


